package handler

// this code below is generated by go-generate do not edit manually
// -----------------------------------------------------------------

type getProductsResponse struct {
	Type string `json:"type"`
}
