package handler

import "github.com/labstack/echo/v4"

// this code below is generated by go-generate do not edit manually
// -----------------------------------------------------------------

func RegisterRoutes(g *echo.Group, h Handler) {
	g.POST("/products", h.CreateProducts)
	g.PUT("/products", h.EditProducts)
}
