package handler

import "github.com/labstack/echo/v4"

// this code below is generated by go-generate do not edit manually
// -----------------------------------------------------------------

func RegisterRoutes(g *echo.Group, h Handler) {
	g.POST("/products", h.CreateProducts)
	g.GET("/products", h.GetProducts)
	g.GET("/productsById", h.GetProduct)
	g.PUT("/products", h.UpdateProduct)
	g.DELETE("/products", h.DeleteProduct)
}
