// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/products": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "description": "request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/EditProductsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/EditProductsOKResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/EditProductsBadRequestResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "description": "request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateProductsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/CreateProductsOKResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/CreateProductsBadRequestResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "CreateProductsBadRequestDataResponse": {
            "type": "object",
            "properties": {
                "manbank": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "CreateProductsBadRequestResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/CreateProductsBadRequestDataResponse"
                }
            }
        },
        "CreateProductsNameRequest": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                }
            }
        },
        "CreateProductsOKResponse": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                }
            }
        },
        "CreateProductsPriceRequest": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "integer"
                }
            }
        },
        "CreateProductsRequest": {
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "name": {
                    "$ref": "#/definitions/CreateProductsNameRequest"
                },
                "price": {
                    "$ref": "#/definitions/CreateProductsPriceRequest"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "EditProductsBadRequestDataResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "EditProductsBadRequestResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/EditProductsBadRequestDataResponse"
                }
            }
        },
        "EditProductsNameRequest": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                }
            }
        },
        "EditProductsOKDataResponse": {
            "type": "object",
            "properties": {
                "state": {
                    "type": "string"
                },
                "workflow_id": {
                    "type": "integer"
                }
            }
        },
        "EditProductsOKResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/EditProductsOKDataResponse"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "EditProductsPriceRequest": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "integer"
                }
            }
        },
        "EditProductsRequest": {
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "name": {
                    "$ref": "#/definitions/EditProductsNameRequest"
                },
                "price": {
                    "$ref": "#/definitions/EditProductsPriceRequest"
                },
                "type": {
                    "type": "string"
                }
            }
        }
    },
    "tags": [
        {
            "description": "API For Frontend only. Please aware that this API keeps changing by new requirements.",
            "name": "API For Frontend"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Service Name",
	Description:      "Description of the service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
