package handlertp

import "fmt"

var TemplateGenerate = fmt.Sprintf(`
package %s

// this code below is generated by go-generate do not edit manually
// -----------------------------------------------------------------

`, PackageNameReplaceName)

var Template = fmt.Sprintf(`
package %s

import (
	"net/http"

	"github.com/labstack/echo/v4"

	"github.com/go-playground/validator/v10"

	"%s"
)

%s
func (h Handler) %s(ctx echo.Context) error {
	%s
	%s
	%s
}
`, PackageNameReplaceName,
	ModuleReplaceName,
	SwagGoReplaceName,
	HandlerFuncNameReplaceName,
	RequestBindReplaceName,
	RequestValidationReplaceName,
	ReturnSuccessReplaceName,
)

var HandlerMainTemplate = fmt.Sprintf(`
package %s

type Handler struct {
}

func NewHandler() Handler {
	return Handler{}
}
`, PackageNameReplaceName)
