package handlertp

const TemplateGenerate = `
package handlertp

// this code below is generated by go-generate do not edit manually
// -----------------------------------------------------------------

`

const Template = `
package handlertp

import (
	"net/http"

	"github.com/labstack/echo/v4"

	"github.com/go-playground/validator/v10"

	"#moduleName#"
)

#swaggo#
func (h Handler) #handlerFuncName#(ctx echo.Context) error {
	#requestBind#
	#requestValidation#
	#returnSuccess#
}
`

const HandlerMainTemplate = `
package handlertp

type Handler struct {
}

func NewHandler() Handler {
	return Handler{}
}
`
