package handlertp

import "fmt"

var RouteTemplate = fmt.Sprintf(`
package %s

import "github.com/labstack/echo/v4"

// this code below is generated by go-generate do not edit manually
// -----------------------------------------------------------------

func RegisterRoutes(g *echo.Group, h Handler) {
	%s	
}
`, PackageNameReplaceName,
	RouteReplaceName,
)

var EchoRouteTemplate = fmt.Sprintf(`g.%s("%s", h.%s)`,
	HandlerMethodReplaceName,
	HandlerRouteReplaceName,
	HandlerFuncNameReplaceName,
)
