package handlertp

const RouteTemplate = `
package handlertp

import "github.com/labstack/echo/v4"

// this code below is generated by go-generate do not edit manually
// -----------------------------------------------------------------

func RegisterRoutes(g *echo.Group, h Handler) {
	#route#
}
`

const EchoRouteTemplate = `g.#handlerMethod#("#handlerRoute#", h.#handlerFuncName#)`
