package dto

// this code below is generated by go-generate do not edit manually
// -----------------------------------------------------------------

type CreateProductsRequest struct {
	Type string `json:"type" validate:"required"`
} // @name CreateProductsRequest

type CreateProductsResponse struct {
	Type string `json:"type"`
} // @name CreateProductsResponse
