package dto

// this code below is generated by go-generate do not edit manually
// -----------------------------------------------------------------

type DeleteProductDataResponse struct {
	MyData DeleteProductDataMyDataResponse `json:"my_data"`
} // @name DeleteProductDataResponse

type DeleteProductDataMyDataResponse struct {
	Type string `json:"type"`
} // @name DeleteProductDataMyDataResponse

type DeleteProductResponse struct {
	Data DeleteProductDataResponse `json:"data"`
} // @name DeleteProductResponse
