package dto

// this code below is generated by go-generate do not edit manually
// -----------------------------------------------------------------

type EditProductsRequest struct {
	Type  string                   `json:"type" validate:"required"`
	Name  EditProductsNameRequest  `json:"name"`
	Price EditProductsPriceRequest `json:"price"`
} // @name EditProductsRequest

type EditProductsNameRequest struct {
	Type string `json:"type"`
} // @name EditProductsNameRequest

type EditProductsPriceRequest struct {
	Type int `json:"type"`
} // @name EditProductsPriceRequest

type EditProductsOKResponse struct {
	Success bool                       `json:"success"`
	Data    EditProductsOKDataResponse `json:"data"`
} // @name EditProductsOKResponse

type EditProductsOKDataResponse struct {
	WorkflowId int    `json:"workflow_id"`
	State      string `json:"state"`
} // @name EditProductsOKDataResponse

type EditProductsBadRequestResponse struct {
	Data EditProductsBadRequestDataResponse `json:"data"`
} // @name EditProductsBadRequestResponse

type EditProductsBadRequestDataResponse struct {
	Type    string `json:"type"`
	Message string `json:"message"`
} // @name EditProductsBadRequestDataResponse
