package dto

// this code below is generated by go-generate do not edit manually
// -----------------------------------------------------------------

type GetProductsResponse struct {
	Type string `json:"type"`
} // @name GetProductsResponse
