package dto

// this code below is generated by go-generate do not edit manually
// -----------------------------------------------------------------

type GetProductResponse struct {
	Type string `json:"type"`
} // @name GetProductResponse
