package dto

// this code below is generated by go-generate do not edit manually
// -----------------------------------------------------------------

type UpdateProductRequest struct {
	Type string `json:"type" validate:"required"`
} // @name UpdateProductRequest

type UpdateProductResponse struct {
	Type string `json:"type"`
} // @name UpdateProductResponse
